module.exports = {
  root: true,
  env: { browser: true, es2020: true },
  settings: {
    "import/resolver": {
      node: {
        extensions: [".js", ".jsx", ".ts", ".tsx"],
      },
    },
  },
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react-hooks/recommended",
  ],
  ignorePatterns: ["dist", ".eslintrc.cjs"],
  parser: "@typescript-eslint/parser",
  plugins: ["react-refresh", "import"],
  rules: {
    "react/prop-types": "off",
    "@typescript-eslint/ban-ts-comment": 0,
    "@typescript-eslint/no-non-null-assertion": 0,
    "cypress/no-unnecessary-waiting": 0,
    "no-console": "error",
    "no-alert": "error",
    "@typescript-eslint/no-explicit-any": 0,
    "react/display-name": 0,
    "react-hooks/exhaustive-deps": 0,
    "sort-imports": "off",
    "import/no-duplicates": "error",
    "react/jsx-no-target-blank": 0,
    "no-useless-return": "error",
    "no-return-await": "error",
    "no-else-return": "error",
    "@typescript-eslint/no-var-requires": 0,
    "no-async-promise-executor": 0,
    "import/no-named-as-default": 0,
    "@typescript-eslint/explicit-module-boundary-types": 0,
    "react/jsx-uses-react": 0,
    "react/react-in-jsx-scope": 0,
    "import/no-unresolved": [2, { caseSensitive: false }],
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": ["error"],
    "react/react-in-jsx-scope": "off",
    "react-refresh/only-export-components": [
      "warn",
      { allowConstantExport: true },
    ],
  },
};
